export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_MESSAGE_REPONSE = "GET_MESSAGE_REPONSE";

export const UPDATE_MESSAGE_REQUEST = "UPDATE_MESSAGE_REQUEST";
export const UPDATE_MESSAGE_RESPONSE = "UPDATE_MESSAGE_RESPONSE";

export const CREATE_MESSAGE_RESPONSE = "CREATE_MESSAGE_RESPONSE";

export const DELETE_MESSAGE_RESPONSE = "DELETE_MESSAGE_RESPONSE";

export const SEARCH_MESSAGE_RESPONSE = "SEARCH_MESSAGE_RESPONSE";
